//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foneMe.SL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallConnection
    {
        public long CallConnectionId { get; set; }
        public string DialerNumber { get; set; }
        public string ReceiverNumber { get; set; }
        public Nullable<long> StatusProfileId { get; set; }
        public string ChannelName { get; set; }
        public string CallType { get; set; }
        public string AppType { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> DialerUserId { get; set; }
        public Nullable<System.Guid> ReceiverUserId { get; set; }
        public Nullable<long> ReceiverStatusProfileId { get; set; }
        public Nullable<long> CallNotificationProfileId { get; set; }
        public Nullable<System.DateTime> CallEndTime { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Profile Profile1 { get; set; }
        public virtual Profile Profile2 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
