//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foneMe.SL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public long ContactId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<long> AreaId { get; set; }
        public string Description { get; set; }
        public Nullable<long> ContactCategoryProfileId { get; set; }
        public Nullable<long> ContactTypeProfileId { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CountryCode { get; set; }
        public string NumberWithOutCode { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Profile Profile1 { get; set; }
        public virtual User User { get; set; }
    }
}
