//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foneMe.SL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class foneMeEntities : DbContext
    {
        public foneMeEntities()
            : base("name=foneMeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audience> Audiences { get; set; }
        public virtual DbSet<CallConnection> CallConnections { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ExternalLogin> ExternalLogins { get; set; }
        public virtual DbSet<LocalContact> LocalContacts { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<ProfileType> ProfileTypes { get; set; }
        public virtual DbSet<ProjectFile> ProjectFiles { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
