//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foneMe.SL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalContact
    {
        public long LocalContactsId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> LocalContactUserId { get; set; }
        public Nullable<System.Guid> HaveContactsUserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
