//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foneMe.SL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectFile
    {
        public long ProjectFileId { get; set; }
        public Nullable<long> PathProfileId { get; set; }
        public string FileName { get; set; }
        public Nullable<long> FileTypeProfileId { get; set; }
        public Nullable<long> FileSize { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> BrandLocationId { get; set; }
        public Nullable<long> ProductId { get; set; }
    }
}
